Update gridsome.server.js missing fields on Author
Error on encountered on netlify build


An error occurred while executing page-query for src/templates/BlogPost.vue
Error: Cannot query field "avatar" on type "Author".
GraphQL request:29:7
28 |       path,
29 |       avatar (width: 60)